name: smart_reference
description: |
  Smart Reference(Smart Pointer) object for Flutter.
version: 0.0.1
homepage: https://github.com/vivitainc/flutter_smart_reference

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  runtime_assert: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
