name: smart_reference
description: Utils for Flutter app.
version: 0.0.2
homepage: https://github.com/vivitainc/flutter_smart_reference
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  tuple: ^2.0.0
  crypto: ^3.0.1
  semaphore: ^0.2.0
  dartx: ^1.0.0
  runtime_assert: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
