name: "Flutter: Package testing"
on:
  push:
jobs:
  flutter-library-test:
    name: "Flutter: Package testing"
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.event.head_commit.message, 'wip:') == false
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v3
      - name: "install / flutter / configure"
        uses: kuhnroyal/flutter-fvm-config-action@v1
      - name: "install / flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      - name: "flutter / build / setup"
        run: |
          flutter pub get
      - name: "flutter / test / format"
        run: |
          flutter format lib/ --set-exit-if-changed --dry-run
          flutter format flutter_test/ --set-exit-if-changed --dry-run
      - name: "flutter / test / analyze"
        run: |
          flutter analyze
      - name: "flutter / test / unit test"
        run: |
          flutter test flutter_test/
